package main

// BaseTemplate 生成基础文件（接口定义 + GetLocalizations 函数）
const BaseTemplate = `// Code generated by gen-l10n. DO NOT EDIT.
package {{.PackageName}}

// {{.CommentAppLocalizationsInterface}}
type AppLocalizations interface {
{{- range .Keys }}
	{{ .MethodName }}() string
{{- end }}
}

// {{.CommentGetLocalizations}}
func GetLocalizations(locale string) AppLocalizations {
	switch locale {
	{{- range .Locales }}
	case "{{ .ID }}":
		return &appLocalizations{{ .StructSuffix }}{}
	{{- end }}
	default:
		// Fallback
		return &appLocalizations{{ .DefaultStructSuffix }}{}
	}
}
`

// LocaleTemplate 生成单个语言实现文件
const LocaleTemplate = `// Code generated by gen-l10n. DO NOT EDIT.
package {{.PackageName}}

// {{.CommentLocaleImplementation}}
type appLocalizations{{.Locale.StructSuffix}} struct{}

{{range $keyMeta := .Keys}}
func (l *appLocalizations{{$.Locale.StructSuffix}}) {{$keyMeta.MethodName}}() string {
	{{- $trans := index $.Locale.Translations $keyMeta.Key }}
	{{- if $trans }}
	return {{$trans}}
	{{- else }}
	return "{{$keyMeta.Key}}"
	{{- end }}
}
{{- end}}
`
