// Code generated by gen-l10n. DO NOT EDIT.
package l10n

// Defines the interface for all supported localized strings
type AppLocalizations interface {
	ErrorExecuteBaseTemplate() string
	CommentGetLocalizations() string
	CliFlagDir() string
	ErrorFormatBaseCode() string
	ErrorExecuteLocaleTemplate() string
	ErrorFormatLocaleCode() string
	CommentAppLocalizationsInterface() string
	ErrorParseLocaleTemplate() string
	CliFlagPkg() string
	InfoExecutionParams() string
	ErrorFindArbFiles() string
	CommentLocaleImplementation() string
	ErrorReadArbFile() string
	ErrorParseArbFile() string
	SuccessGeneratedCode() string
	ErrorNoArbFiles() string
	ErrorWriteLocaleFile() string
	InfoTemplateData() string
	ErrorParseBaseTemplate() string
	ErrorWriteBaseFile() string
}

// Returns the localization instance based on locale code
func GetLocalizations(locale string) AppLocalizations {
	switch locale {
	case "en":
		return &appLocalizationsEn{}
	case "ja":
		return &appLocalizationsJa{}
	case "zh":
		return &appLocalizationsZh{}
	case "zh_Hant":
		return &appLocalizationsZhHant{}
	default:
		// Fallback
		return &appLocalizationsEn{}
	}
}
