// Code generated by gen-l10n. DO NOT EDIT.
package l10n

// Defines the interface for all supported localized strings
type AppLocalizations interface {
	CliFlagDir() string
	CliFlagPkg() string
	CommentAppLocalizationsInterface() string
	CommentGetLocalizations() string
	CommentLocaleImplementation() string
	ErrorExecuteBaseTemplate() string
	ErrorExecuteLocaleTemplate() string
	ErrorFindArbFiles() string
	ErrorFormatBaseCode() string
	ErrorFormatLocaleCode() string
	ErrorNoArbFiles() string
	ErrorParseArbFile() string
	ErrorParseBaseTemplate() string
	ErrorParseLocaleTemplate() string
	ErrorReadArbFile() string
	ErrorWriteBaseFile() string
	ErrorWriteLocaleFile() string
	InfoExecutionParams() string
	InfoTemplateData() string
	SuccessGeneratedCode() string
}

// Returns the localization instance based on locale code
func GetLocalizations(locale string) AppLocalizations {
	switch locale {
	case "en":
		return &appLocalizationsEn{}
	case "ja":
		return &appLocalizationsJa{}
	case "zh":
		return &appLocalizationsZh{}
	case "zh_Hant":
		return &appLocalizationsZhHant{}
	default:
		// Fallback
		return &appLocalizationsEn{}
	}
}
