// Code generated by gen-l10n. DO NOT EDIT.
package l10n

// Defines the interface for all supported localized strings
type AppLocalizations interface {
	ErrorParseLocaleTemplate() string
	CliFlagDir() string
	CliFlagPkg() string
	InfoExecutionParams() string
	ErrorNoArbFiles() string
	ErrorFormatBaseCode() string
	ErrorExecuteLocaleTemplate() string
	CommentAppLocalizationsInterface() string
	ErrorWriteBaseFile() string
	SuccessGeneratedCode() string
	ErrorParseBaseTemplate() string
	CommentGetLocalizations() string
	ErrorWriteLocaleFile() string
	CommentLocaleImplementation() string
	ErrorFormatLocaleCode() string
	InfoTemplateData() string
	ErrorParseArbFile() string
	ErrorFindArbFiles() string
	ErrorReadArbFile() string
	ErrorExecuteBaseTemplate() string
}

// Returns the localization instance based on locale code
func GetLocalizations(locale string) AppLocalizations {
	switch locale {
	case "en":
		return &appLocalizationsEn{}
	case "ja":
		return &appLocalizationsJa{}
	case "zh":
		return &appLocalizationsZh{}
	case "zh_Hant":
		return &appLocalizationsZhHant{}
	default:
		// Fallback
		return &appLocalizationsEn{}
	}
}
