// Code generated by gen-l10n. DO NOT EDIT.
package l10n

// Locale implementation: en
type appLocalizationsEn struct{}

func (l *appLocalizationsEn) ErrorParseLocaleTemplate() string {
	return "Failed to parse locale template: %v"
}
func (l *appLocalizationsEn) CliFlagDir() string {
	return "l10n dir"
}
func (l *appLocalizationsEn) CliFlagPkg() string {
	return "package name"
}
func (l *appLocalizationsEn) InfoExecutionParams() string {
	return "Execution parameters: dir=%s, pkg=%s"
}
func (l *appLocalizationsEn) ErrorNoArbFiles() string {
	return "No app_*.arb files found in directory %s"
}
func (l *appLocalizationsEn) ErrorFormatBaseCode() string {
	return "Failed to format base code: %v\nCode content:\n%s"
}
func (l *appLocalizationsEn) ErrorExecuteLocaleTemplate() string {
	return "Failed to execute locale template (%s): %v"
}
func (l *appLocalizationsEn) CommentAppLocalizationsInterface() string {
	return "Defines the interface for all supported localized strings"
}
func (l *appLocalizationsEn) ErrorWriteBaseFile() string {
	return "Failed to write base file: %v"
}
func (l *appLocalizationsEn) SuccessGeneratedCode() string {
	return "Generated localization code: %s"
}
func (l *appLocalizationsEn) ErrorParseBaseTemplate() string {
	return "Failed to parse base template: %v"
}
func (l *appLocalizationsEn) CommentGetLocalizations() string {
	return "Returns the localization instance based on locale code"
}
func (l *appLocalizationsEn) ErrorWriteLocaleFile() string {
	return "Failed to write locale file (%s): %v"
}
func (l *appLocalizationsEn) CommentLocaleImplementation() string {
	return "Locale implementation: %s"
}
func (l *appLocalizationsEn) ErrorFormatLocaleCode() string {
	return "Failed to format locale code (%s): %v\nCode content:\n%s"
}
func (l *appLocalizationsEn) InfoTemplateData() string {
	return "Template data: %+v"
}
func (l *appLocalizationsEn) ErrorParseArbFile() string {
	return "Failed to parse ARB file: path=%s, error=%v"
}
func (l *appLocalizationsEn) ErrorFindArbFiles() string {
	return "Failed to find ARB files: %v"
}
func (l *appLocalizationsEn) ErrorReadArbFile() string {
	return "Failed to read ARB file: path=%s, error=%v"
}
func (l *appLocalizationsEn) ErrorExecuteBaseTemplate() string {
	return "Failed to execute base template: %v"
}
